---
# Role metadata for wallix-global-domains

galaxy_info:
  author: WALLIX Automation Team
  description: Ansible role for managing WALLIX Bastion global domains
  company: WALLIX
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - "bionic"
        - "focal" 
        - "jammy"
    - name: Debian
      versions:
        - "buster"
        - "bullseye"
  galaxy_tags:
    - security
    - bastion
    - wallix
    - domain
    - privileged access

# Role dependencies
dependencies:
  - role: wallix-auth
    when: wallix_session_cookie is not defined