---
# Generate domains report for WALLIX

- name: "Domains | Report | Gather domain status"
  set_fact:
    domains_report_data:
      auth_domains_status:
        managed: "{{ wallix_domains.manage_auth_domains | default(true) }}"
        count: "{{ wallix_auth_domains | default({}) | length }}"
        timestamp: "{{ ansible_date_time.iso8601 }}"
      ldap_domains_status:
        managed: "{{ wallix_domains.manage_ldap_domains | default(true) }}"
        count: 0
        timestamp: "{{ ansible_date_time.iso8601 }}"
      ad_domains_status:
        managed: "{{ wallix_domains.manage_ad_domains | default(true) }}"
        count: 0
        timestamp: "{{ ansible_date_time.iso8601 }}"
      radius_domains_status:
        managed: "{{ wallix_domains.manage_radius_domains | default(true) }}"
        count: 0
        timestamp: "{{ ansible_date_time.iso8601 }}"
      global_domains_status:
        managed: "{{ wallix_domains.manage_global_domains | default(true) }}"
        count: 0
        timestamp: "{{ ansible_date_time.iso8601 }}"
      report_info:
        role: "wallix-domains"
        operation_mode: "{{ wallix_domains.operation_mode | default('apply') }}"
        hostname: "{{ inventory_hostname }}"
        ansible_version: "{{ ansible_version.full }}"
        timestamp: "{{ ansible_date_time.iso8601 }}"
      validation_status:
        domains_validated: "{{ wallix_domains_validated | default(false) }}"
        test_passed: "{{ wallix_domains_test_passed | default(false) }}"

- name: "Domains | Report | Generate domains report filename"
  set_fact:
    domains_report_filename: "wallix_domains_report_{{ inventory_hostname }}_{{ ansible_date_time.epoch }}.json"

- name: "Domains | Report | Save domains report"
  copy:
    content: "{{ domains_report_data | to_nice_json }}"
    dest: "/tmp/{{ domains_report_filename }}"
    mode: '0644'
  when: wallix_domains.detailed_logging | default(true)

- name: "Domains | Report | Display report summary"
  debug:
    msg:
      - "Domains Report Summary:"
      - "======================"
      - "Auth Domains Managed: {{ domains_report_data.auth_domains_status.managed }}"
      - "LDAP Domains Managed: {{ domains_report_data.ldap_domains_status.managed }}"
      - "AD Domains Managed: {{ domains_report_data.ad_domains_status.managed }}"
      - "RADIUS Domains Managed: {{ domains_report_data.radius_domains_status.managed }}"
      - "Global Domains Managed: {{ domains_report_data.global_domains_status.managed }}"
      - "Report saved to: /tmp/{{ domains_report_filename }}"

- name: "Domains | Report | Set final status"
  set_fact:
    wallix_domains_completed: true
    wallix_domains_completion_time: "{{ ansible_date_time.iso8601 }}"
    wallix_domains_report_file: "/tmp/{{ domains_report_filename }}"
    wallix_domains_report_generated: true