---
# Handlers for wallix-auth role

- name: cleanup wallix session
  uri:
    url: "{{ wallix_api.base_url }}/logout"
    method: POST
    headers:
      Cookie: "{{ wallix_session_cookie | default('') }}"
    validate_certs: "{{ wallix_auth.connection.verify_ssl }}"
    timeout: "{{ wallix_auth.connection.timeout }}"
    status_code: [200, 204, 404]
  ignore_errors: true
  when: wallix_session_cookie is defined

- name: remove session cookie file
  file:
    path: "{{ wallix_auth.session.cookie_file }}"
    state: absent
  ignore_errors: true
  when: wallix_auth.session.cookie_file is defined