---
# Main tasks for wallix-auth role

- name: Validate authentication configuration
  assert:
    that:
      - wallix_auth.initial_auth_method in ['credentials', 'api_key']
      - (wallix_auth.initial_auth_method == 'credentials' and wallix_auth.credentials.username is defined and wallix_auth.credentials.password is defined) or (wallix_auth.initial_auth_method == 'api_key' and wallix_auth.api_key.key is defined)
    fail_msg: "Invalid authentication configuration. Please check your credentials or API key settings."
    success_msg: "Authentication configuration validated successfully."

- name: Include authentication tasks
  include_tasks: authenticate.yml

- name: Include session management tasks
  include_tasks: session_management.yml
  when: wallix_auth.session.use_cookie | default(true)

- name: Validate API connectivity
  include_tasks: validate_connectivity.yml