---
# Create and manage WALLIX devices

- name: Create devices on WALLIX
  uri:
    url: "{{ wallix_api.base_url }}/devices"
    method: POST
    headers:
      Cookie: "{{ wallix_session_cookie }}"
      Content-Type: "application/json"
    body_format: json
    body:
      device_name: "{{ item.name }}"
      description: "{{ item.description | default('') }}"
      host: "{{ item.host }}"
      alias: "{{ item.alias | default(item.name) }}"
    validate_certs: "{{ wallix_auth.connection.verify_ssl }}"
    timeout: "{{ wallix_auth.connection.timeout }}"
    status_code: [200, 201, 204, 409]  # 204 = No Content (success), 409 = already exists
    return_content: yes
  register: device_creation_result
  loop: "{{ wallix_devices }}"
  when: 
    - item.state | default('present') == 'present'
    - wallix_devices_mode != 'dry_run'

- name: Debug device creation results
  debug:
    msg:
      - "Device: {{ item.item.name }}"
      - "Status: {{ item.status }}"
      - "Result: {{ 'Created' if item.status == 201 else ('Already exists' if item.status == 409 else 'Updated') }}"
  loop: "{{ device_creation_result.results }}"
  when: 
    - device_creation_result.results is defined
    - wallix_devices_debug.enabled | default(false)

- name: Get existing devices for validation
  uri:
    url: "{{ wallix_api.base_url }}/devices"
    method: GET
    headers:
      Cookie: "{{ wallix_session_cookie }}"
    validate_certs: "{{ wallix_auth.connection.verify_ssl }}"
    timeout: "{{ wallix_auth.connection.timeout }}"
    status_code: [200]
    return_content: yes
  register: existing_devices

- name: Set device creation status
  set_fact:
    wallix_devices_status: "success"
    wallix_devices_created: "{{ device_creation_result.results | selectattr('status', 'equalto', 201) | list | length }}"
    wallix_devices_updated: "{{ device_creation_result.results | selectattr('status', 'equalto', 200) | list | length }}"
    wallix_devices_existing: "{{ device_creation_result.results | selectattr('status', 'equalto', 409) | list | length }}"
  when: device_creation_result.results is defined

- name: Display devices creation summary
  debug:
    msg:
      - "✅ Device management completed successfully"
      - "Created: {{ wallix_devices_created | default(0) }}"
      - "Updated: {{ wallix_devices_updated | default(0) }}" 
      - "Already existing: {{ wallix_devices_existing | default(0) }}"
      - "Total devices in WALLIX: {{ existing_devices.json | length }}"