---
# Infrastructure definition for WALLIX Bastion automation

# Authentication domains
auth_domains:
  - name: "corporate_ad"
    type: "AD"
    description: "Corporate Active Directory"
    server: "dc.example.com"
    port: 389
    base_dn: "DC=example,DC=com"
    user_filter: "(&(objectClass=user)(sAMAccountName={0}))"
    ssl: false
    mappings:
      - external_group: "Domain Admins"
        local_group: "Administrators"
      - external_group: "IT Team"
        local_group: "Operators"

# Global domains
global_domains:
  - name: "production_domain"
    description: "Domain for production accounts"
    password_change_policy: "strict_policy"
  
  - name: "development_domain"
    description: "Domain for development accounts"
    password_change_policy: "standard_policy"

# User groups
user_groups:
  - name: "Administrators"
    description: "System administrators with full access"
    profile: "product_administrator"
  
  - name: "Operators"
    description: "System operators with limited access"
    profile: "operator"
  
  - name: "Auditors"
    description: "Audit team with read-only access"
    profile: "auditor"
  
  - name: "Developers"
    description: "Development team"
    profile: "operator"

# Users
users:
  - username: "john.admin"
    email: "john.admin@example.com"
    first_name: "John"
    last_name: "Administrator"
    groups: ["Administrators"]
    auth_domain: "corporate_ad"
    mfa_required: true
    
  - username: "jane.operator"
    email: "jane.operator@example.com"
    first_name: "Jane"
    last_name: "Operator"
    groups: ["Operators"]
    auth_domain: "corporate_ad"
    mfa_required: true
    
  - username: "bob.developer"
    email: "bob.developer@example.com"
    first_name: "Bob"
    last_name: "Developer"
    groups: ["Developers"]
    auth_domain: "corporate_ad"
    mfa_required: false

# Target groups
target_groups:
  - name: "Production Servers"
    description: "All production servers"
    
  - name: "Development Servers"
    description: "All development servers"
    
  - name: "Database Servers"
    description: "All database servers"
    
  - name: "Web Servers"
    description: "All web servers"

# Devices
devices:
  - name: "web-server-01"
    host: "10.0.1.10"
    description: "Production web server"
    tags: ["production", "web", "ubuntu"]
    target_groups: ["Production Servers", "Web Servers"]
    services:
      - name: "SSH"
        port: 22
        protocol: "SSH"
        connection_policy: "SSH_Strict"
        subprotocols: ["SSH_SHELL_SESSION", "SCP_UP", "SCP_DOWN"]
    local_domains:
      - name: "local"
        accounts:
          - name: "root"
            password: "{{ vault_web01_root_password }}"
          - name: "deploy"
            ssh_key: "{{ deploy_ssh_key }}"
            
  - name: "db-server-01"
    host: "10.0.2.10"
    description: "Production database server"
    tags: ["production", "database", "postgresql"]
    target_groups: ["Production Servers", "Database Servers"]
    services:
      - name: "SSH"
        port: 22
        protocol: "SSH"
        connection_policy: "SSH_Strict"
      - name: "PostgreSQL"
        port: 5432
        protocol: "RAWTCPIP"
        connection_policy: "RAWTCPIP"
    local_domains:
      - name: "local"
        accounts:
          - name: "postgres"
            password: "{{ vault_db01_postgres_password }}"
            
  - name: "dev-server-01"
    host: "10.0.3.10"
    description: "Development server"
    tags: ["development", "test"]
    target_groups: ["Development Servers"]
    services:
      - name: "SSH"
        port: 22
        protocol: "SSH"
        connection_policy: "SSH_Standard"

# Applications
applications:
  - name: "prod-webapp"
    host: "webapp.example.com"
    description: "Production web application"
    connection_policy: "HTTPS"
    tags: ["production", "webapp"]
    target_groups: ["Production Servers"]
    local_domains:
      - name: "local"
        accounts:
          - name: "appuser"
            password: "{{ vault_webapp_password }}"