---
# Security policies for WALLIX Bastion automation

# Connection policies
connection_policies:
  - name: "SSH_Strict"
    type: "SSH"
    description: "Strict SSH policy for production servers"
    options:
      algorithms:
        cipher_algos: "aes256-gcm@openssh.com,aes128-gcm@openssh.com"
        kex_algos: "diffie-hellman-group16-sha512,ecdh-sha2-nistp521"
        mac_algos: "hmac-sha2-256,hmac-sha2-512"
      session:
        inactivity_timeout: 1800  # 30 minutes
        max_session_time: 7200    # 2 hours
        recording_enabled: true
      authentication:
        show_issue_banner: true
        banner_text: "Authorized access only. All activities are monitored."
      security:
        disable_x11_forwarding: true
        disable_agent_forwarding: true
        
  - name: "SSH_Standard"
    type: "SSH"
    description: "Standard SSH policy for development servers"
    options:
      session:
        inactivity_timeout: 3600  # 1 hour
        max_session_time: 14400   # 4 hours
        recording_enabled: true
      authentication:
        show_issue_banner: true
        banner_text: "Development environment. Please follow security guidelines."
        
  - name: "RDP_Strict"
    type: "RDP"
    description: "Strict RDP policy for Windows servers"
    options:
      session:
        inactivity_timeout: 1800
        max_session_time: 7200
        recording_enabled: true
      security:
        clipboard_up: false
        clipboard_down: false
        
  - name: "HTTPS"
    type: "HTTPS"
    description: "HTTPS policy for web applications"
    options:
      session:
        inactivity_timeout: 3600
        recording_enabled: true

# Password checkout policies
checkout_policies:
  - name: "Standard_Checkout"
    description: "Standard password checkout policy"
    max_duration: 3600        # 1 hour
    auto_checkin: true
    approval_required: false
    notifications:
      on_checkout: true
      on_checkin: true
      
  - name: "Production_Checkout"
    description: "Checkout policy for production accounts"
    max_duration: 1800        # 30 minutes
    auto_checkin: true
    approval_required: true
    notifications:
      on_checkout: true
      on_checkin: true
      on_approval: true
      
  - name: "Emergency_Checkout"
    description: "Emergency checkout for critical situations"
    max_duration: 7200        # 2 hours
    auto_checkin: false
    approval_required: true
    notifications:
      on_checkout: true
      on_checkin: true

# Password change policies
password_change_policies:
  - name: "strict_policy"
    description: "Strict password change policy for production"
    change_frequency: 1       # days
    auto_change: true
    complexity_requirements:
      min_length: 16
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_symbols: true
      exclude_dictionary_words: true
    notifications:
      on_change: true
      on_failure: true
      
  - name: "standard_policy"
    description: "Standard password change policy"
    change_frequency: 7       # days
    auto_change: true
    complexity_requirements:
      min_length: 12
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_symbols: true
    notifications:
      on_change: false
      on_failure: true

# Time frames
timeframes:
  - name: "Business_Hours"
    description: "Monday to Friday, 8AM to 6PM"
    periods:
      - days: "mon,tue,wed,thu,fri"
        start_time: "08:00"
        end_time: "18:00"
        
  - name: "Extended_Hours"
    description: "Monday to Friday, 7AM to 9PM"
    periods:
      - days: "mon,tue,wed,thu,fri"
        start_time: "07:00"
        end_time: "21:00"
        
  - name: "24x7"
    description: "24 hours, 7 days a week"
    periods:
      - days: "mon,tue,wed,thu,fri,sat,sun"
        start_time: "00:00"
        end_time: "23:59"
        
  - name: "Maintenance_Window"
    description: "Saturday night maintenance window"
    periods:
      - days: "sat"
        start_time: "22:00"
        end_time: "23:59"
      - days: "sun"
        start_time: "00:00"
        end_time: "06:00"

# Authorizations
authorizations:
  - name: "Admin_Full_Access"
    description: "Full access for administrators"
    user_groups: ["Administrators"]
    target_groups: ["Production Servers", "Development Servers", "Database Servers", "Web Servers"]
    timeframe: "24x7"
    session_rights:
      authorize_sessions: true
      kill_sessions: true
      view_passwords: true
    password_rights:
      authorize_password_retrieval: true
      view_passwords: true
    approval_required: false
    
  - name: "Operator_Production_Access"
    description: "Production access for operators"
    user_groups: ["Operators"]
    target_groups: ["Production Servers"]
    timeframe: "Business_Hours"
    session_rights:
      authorize_sessions: true
      kill_sessions: false
      view_passwords: false
    password_rights:
      authorize_password_retrieval: true
      view_passwords: false
    approval_required: true
    
  - name: "Developer_Dev_Access"
    description: "Development access for developers"
    user_groups: ["Developers"]
    target_groups: ["Development Servers"]
    timeframe: "Extended_Hours"
    session_rights:
      authorize_sessions: true
      kill_sessions: false
      view_passwords: false
    password_rights:
      authorize_password_retrieval: false
      view_passwords: false
    approval_required: false
    
  - name: "Auditor_ReadOnly_Access"
    description: "Read-only access for auditors"
    user_groups: ["Auditors"]
    target_groups: ["Production Servers", "Development Servers"]
    timeframe: "Business_Hours"
    session_rights:
      authorize_sessions: false
      kill_sessions: false
      view_passwords: false
    password_rights:
      authorize_password_retrieval: false
      view_passwords: false
    approval_required: false