---
# CronJob pour synchroniser les secrets WALLIX dans Kubernetes
# Synchronisation périodique automatique

# 1. ServiceAccount avec permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallix-secret-sync
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wallix-secret-manager
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wallix-secret-sync-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wallix-secret-manager
subjects:
- kind: ServiceAccount
  name: wallix-secret-sync
  namespace: default

---
# 2. Secret avec la clé API WALLIX
apiVersion: v1
kind: Secret
metadata:
  name: wallix-api-credentials
  namespace: default
type: Opaque
stringData:
  api-key: "YOUR_WALLIX_API_KEY"

---
# 3. ConfigMap avec le script de synchronisation
apiVersion: v1
kind: ConfigMap
metadata:
  name: wallix-sync-script
  namespace: default
data:
  sync.sh: |
    #!/bin/sh
    set -e
    
    echo "WALLIX Secret Synchronization - $(date)"
    
    # Configuration
    BASTION_URL="${BASTION_URL:-https://bastion.example.com}"
    NAMESPACE="${NAMESPACE:-default}"
    
    # Fonction pour récupérer un secret depuis WALLIX
    fetch_wallix_secret() {
      local key="$1"
      local secret_name="$2"
      local secret_key="$3"
      
      echo "Fetching $key from WALLIX..."
      
      PASSWORD=$(curl -s -f \
        -H "X-Auth-Key: $WALLIX_API_KEY" \
        -H "Content-Type: application/json" \
        "$BASTION_URL/api/targetpasswords/checkout/$key" \
        | jq -r '.password')
      
      if [ -z "$PASSWORD" ] || [ "$PASSWORD" = "null" ]; then
        echo "ERROR: Failed to fetch $key"
        return 1
      fi
      
      # Créer ou mettre à jour le secret Kubernetes
      kubectl create secret generic "$secret_name" \
        --from-literal="$secret_key=$PASSWORD" \
        --namespace="$NAMESPACE" \
        --dry-run=client -o yaml | kubectl apply -f -
      
      echo "✓ Secret $secret_name synchronized"
    }
    
    # Synchroniser les secrets
    fetch_wallix_secret "admin@db-postgres@prod.local" "database-credentials" "password"
    fetch_wallix_secret "admin@db-mysql@prod.local" "mysql-credentials" "password"
    fetch_wallix_secret "apiuser@external-api@prod.local" "api-credentials" "api-key"
    fetch_wallix_secret "deploy@gitserver@prod.local" "git-ssh-key" "ssh-key"
    
    echo "Synchronization completed successfully - $(date)"

---
# 4. CronJob de synchronisation
apiVersion: batch/v1
kind: CronJob
metadata:
  name: wallix-secret-sync
  namespace: default
spec:
  # Synchroniser toutes les 15 minutes
  schedule: "*/15 * * * *"
  
  # Conserver l'historique des 3 derniers jobs réussis et 1 échoué
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: wallix-secret-sync
        spec:
          serviceAccountName: wallix-secret-sync
          restartPolicy: OnFailure
          
          containers:
          - name: sync
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - /scripts/sync.sh
            env:
            - name: WALLIX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wallix-api-credentials
                  key: api-key
            - name: BASTION_URL
              value: "https://your-bastion.example.com"
            - name: NAMESPACE
              value: "default"
            volumeMounts:
            - name: sync-script
              mountPath: /scripts
          
          volumes:
          - name: sync-script
            configMap:
              name: wallix-sync-script
              defaultMode: 0755

---
# 5. Job manuel (pour tester la synchronisation)
apiVersion: batch/v1
kind: Job
metadata:
  name: wallix-sync-manual
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: wallix-secret-sync
    spec:
      serviceAccountName: wallix-secret-sync
      restartPolicy: Never
      
      containers:
      - name: sync
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - /scripts/sync.sh
        env:
        - name: WALLIX_API_KEY
          valueFrom:
            secretKeyRef:
              name: wallix-api-credentials
              key: api-key
        - name: BASTION_URL
          value: "https://your-bastion.example.com"
        - name: NAMESPACE
          value: "default"
        volumeMounts:
        - name: sync-script
          mountPath: /scripts
      
      volumes:
      - name: sync-script
        configMap:
          name: wallix-sync-script
          defaultMode: 0755

---
# 6. Exemple d'application utilisant les secrets synchronisés
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-using-synced-secrets
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: app
        image: myapp:latest
        env:
        # Les secrets sont automatiquement synchronisés par le CronJob
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-credentials
              key: api-key
        - name: SSH_KEY
          valueFrom:
            secretKeyRef:
              name: git-ssh-key
              key: ssh-key