---
# WALLIX Bastion SecretStore using Webhook Provider
# ESO v0.20+ - API v1 with template-based authentication
# Based on https://external-secrets.io/latest/provider/webhook/

apiVersion: v1
kind: Secret
metadata:
  name: wallix-api-credentials
  namespace: default
type: Opaque
stringData:
  api-user: "admin"                        # Replace with actual WALLIX API user
  api-key: "YOUR_WALLIX_API_KEY"          # Replace with actual API key

---
# Optional: ConfigMap with WALLIX CA certificate for TLS validation
# Extract certificate: echo | openssl s_client -connect WALLIX:443 -showcerts 2>/dev/null | openssl x509 -outform PEM
apiVersion: v1
kind: ConfigMap
metadata:
  name: wallix-ca
  namespace: default
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    # Replace with your actual WALLIX CA certificate
    -----END CERTIFICATE-----

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: wallix-bastion
  namespace: default
spec:
  provider:
    webhook:
      # WALLIX Bastion API endpoint template
      # Use DNS hostname for proper certificate validation
      url: "https://wallix-bastion.example.com/api/targetpasswords/checkout/{{ .remoteRef.key }}"
      method: GET
      timeout: 30s
      headers:
        Content-Type: "application/json"
        X-Auth-User: "{{ .authUser }}"
        X-Auth-Key: "{{ .authKey }}"
      secrets:
      - name: authUser
        secretRef:
          name: wallix-api-credentials
          key: api-user
      - name: authKey
        secretRef:
          name: wallix-api-credentials
          key: api-key
      result:
        jsonPath: "$.password"
      # TLS validation (required in ESO v0.20+)
      caProvider:
        type: ConfigMap
        name: wallix-ca
        key: ca.crt
        namespace: default

---
# Example ExternalSecret using WALLIX Bastion
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallix-example
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: wallix-bastion
    kind: SecretStore
  target:
    name: wallix-synced-secret
    creationPolicy: Owner
  data:
  - secretKey: admin-password
    remoteRef:
      # WALLIX format: account@target@domain
      key: "admin@server01@prod.local"
