---
# WALLIX Cleanup - Target Groups Cleanup Tasks

- name: "🔍 Cleanup | Get all target groups"
  uri:
    url: "{{ wallix_api.base_url }}/targetgroups"
    method: GET
    headers:
      Cookie: "{{ wallix_session_cookie }}"
    validate_certs: "{{ wallix_auth.connection.verify_ssl | default(false) }}"
    timeout: 30
    status_code: [200]
    return_content: yes
  register: all_target_groups_result

- name: "🗑️ Cleanup | Filter target groups for deletion"
  set_fact:
    target_groups_to_delete: []

- name: "🗑️ Cleanup | Check each target group against include patterns"
  set_fact:
    target_groups_to_delete: "{{ target_groups_to_delete + [item] }}"
  loop: "{{ all_target_groups_result.json | default([]) }}"
  when: 
    - all_target_groups_result.json is defined
    - wallix_cleanup_filters.include_patterns | length > 0
    - item.group_name is match(include_regex)
    - not (item.group_name is match(exclude_regex))
  vars:
    include_regex: "{{ wallix_cleanup_filters.include_patterns | map('replace', '*', '.*') | map('replace', '?', '.') | join('|') }}"
    exclude_regex: "{{ wallix_cleanup_filters.exclude_patterns | map('replace', '*', '.*') | map('replace', '?', '.') | join('|') }}"

- name: "📊 Cleanup | Display target groups to delete"
  debug:
    msg:
      - "Found {{ target_groups_to_delete | length }} target groups to delete"
      - "Target groups: {{ target_groups_to_delete | map(attribute='group_name') | list }}"
  when: 
    - target_groups_to_delete is defined
    - wallix_cleanup_debug.enabled

- name: "🗑️ Cleanup | Delete target group"
  uri:
    url: "{{ wallix_api.base_url }}/targetgroups/{{ item.group_name }}"
    method: DELETE
    headers:
      Cookie: "{{ wallix_session_cookie }}"
    validate_certs: "{{ wallix_auth.connection.verify_ssl | default(false) }}"
    timeout: 30
    status_code: [200, 204, 404]  # 404 = already deleted
    return_content: yes
  register: delete_target_group_result
  loop: "{{ target_groups_to_delete | default([]) }}"
  when: 
    - wallix_cleanup.operation_mode != 'dry_run'
    - wallix_cleanup_components.target_groups.enabled | default(true)
  ignore_errors: "{{ wallix_cleanup_error_handling.continue_on_error }}"

- name: "📈 Cleanup | Update target group deletion stats (dry run)"
  set_fact:
    wallix_cleanup_stats: >-
      {{
        wallix_cleanup_stats | default({}) | combine({
          'target_groups_processed': (target_groups_to_delete | default([]) | length),
          'target_groups_deleted': 0,
          'target_groups_errors': 0
        })
      }}
  when: wallix_cleanup.operation_mode == 'dry_run'

- name: "📈 Cleanup | Update target group deletion stats (real run)"
  set_fact:
    wallix_cleanup_stats: >-
      {{
        wallix_cleanup_stats | default({}) | combine({
          'target_groups_processed': (target_groups_to_delete | default([]) | length),
          'target_groups_deleted': (delete_target_group_result.results | default([]) | selectattr('status', 'in', [200, 204]) | list | length),
          'target_groups_errors': (delete_target_group_result.results | default([]) | selectattr('status', 'ge', 400) | list | length)
        })
      }}
  when: wallix_cleanup.operation_mode != 'dry_run'

- name: "✅ Cleanup | Target group cleanup summary"
  debug:
    msg:
      - "Target group cleanup completed"
      - "Processed: {{ wallix_cleanup_stats.target_groups_processed | default(0) }}"
      - "Deleted: {{ wallix_cleanup_stats.target_groups_deleted | default(0) }}"
      - "Errors: {{ wallix_cleanup_stats.target_groups_errors | default(0) }}"