---
# WALLIX Cleanup - Global Accounts Cleanup Tasks

- name: "🔍 Cleanup | Get all global domains for account cleanup"
  uri:
    url: "{{ wallix_api.base_url }}/domains"
    method: GET
    headers:
      Cookie: "{{ wallix_session_cookie }}"
    validate_certs: "{{ wallix_auth.connection.verify_ssl | default(false) }}"
    timeout: 30
    status_code: [200]
    return_content: yes
  register: all_domains_for_accounts_result

- name: "🔍 Cleanup | Get global accounts for each domain"
  uri:
    url: "{{ wallix_api.base_url }}/domains/{{ item.id }}/accounts"
    method: GET
    headers:
      Cookie: "{{ wallix_session_cookie }}"
    validate_certs: "{{ wallix_auth.connection.verify_ssl | default(false) }}"
    timeout: 30
    status_code: [200]
    return_content: yes
  register: domain_accounts_results
  loop: "{{ all_domains_for_accounts_result.json | default([]) }}"
  when: 
    - all_domains_for_accounts_result.json is defined
    - item.domain_name != "local"  # Skip local domain
  ignore_errors: true

- name: "🗑️ Cleanup | Build list of global accounts to delete"
  set_fact:
    global_accounts_to_delete: []

- name: "🗑️ Cleanup | Filter global accounts for deletion"
  set_fact:
    global_accounts_to_delete: "{{ global_accounts_to_delete + filtered_accounts }}"
  loop: "{{ domain_accounts_results.results | default([]) }}"
  when: 
    - item.json is defined
    - not item.failed | default(false)
  vars:
    include_regex: "{{ wallix_cleanup_filters.include_patterns | map('replace', '*', '.*') | map('replace', '?', '.') | join('|') }}"
    exclude_regex: "{{ wallix_cleanup_filters.exclude_patterns | map('replace', '*', '.*') | map('replace', '?', '.') | join('|') }}"
    filtered_accounts: >-
      {{
        item.json | selectattr('account_name', 'match', include_regex) |
        rejectattr('account_name', 'match', exclude_regex) |
        map('combine', {'domain_id': item.item.id, 'domain_name': item.item.domain_name}) |
        list
      }}

- name: "📊 Cleanup | Display global accounts to delete"
  debug:
    msg:
      - "Found {{ global_accounts_to_delete | length }} global accounts to delete"
      - "Accounts: {{ global_accounts_to_delete | map(attribute='account_name') | list }}"
  when: 
    - global_accounts_to_delete is defined
    - wallix_cleanup_debug.enabled | default(true)

- name: "🗑️ Cleanup | Delete global account"
  uri:
    url: "{{ wallix_api.base_url }}/domains/{{ item.domain_id }}/accounts/{{ item.account_name }}"
    method: DELETE
    headers:
      Cookie: "{{ wallix_session_cookie }}"
    validate_certs: "{{ wallix_auth.connection.verify_ssl | default(false) }}"
    timeout: 30
    status_code: [200, 204, 404]  # 404 = already deleted
    return_content: yes
  register: delete_global_account_result
  loop: "{{ global_accounts_to_delete | default([]) }}"
  when: 
    - wallix_cleanup.operation_mode != 'dry_run'
    - wallix_cleanup_components.global_accounts.enabled | default(true)
  ignore_errors: "{{ wallix_cleanup_error_handling.continue_on_error | default(true) }}"

- name: "📈 Cleanup | Update global account deletion stats (dry run)"
  set_fact:
    wallix_cleanup_stats: >-
      {{
        wallix_cleanup_stats | default({}) | combine({
          'global_accounts_processed': (global_accounts_to_delete | default([]) | length),
          'global_accounts_deleted': 0,
          'global_accounts_errors': 0
        })
      }}
  when: wallix_cleanup.operation_mode == 'dry_run'

- name: "📈 Cleanup | Update global account deletion stats (real run)"
  set_fact:
    wallix_cleanup_stats: >-
      {{
        wallix_cleanup_stats | default({}) | combine({
          'global_accounts_processed': (global_accounts_to_delete | default([]) | length),
          'global_accounts_deleted': (delete_global_account_result.results | default([]) | selectattr('status', 'in', [200, 204]) | list | length),
          'global_accounts_errors': (delete_global_account_result.results | default([]) | selectattr('status', 'ge', 400) | list | length)
        })
      }}
  when: wallix_cleanup.operation_mode != 'dry_run'

- name: "✅ Cleanup | Global account cleanup summary"
  debug:
    msg:
      - "Global account cleanup completed"
      - "Processed: {{ wallix_cleanup_stats.global_accounts_processed | default(0) }}"
      - "Deleted: {{ wallix_cleanup_stats.global_accounts_deleted | default(0) }}"
      - "Errors: {{ wallix_cleanup_stats.global_accounts_errors | default(0) }}"