---
# discover_device_accounts.yml - Discover local accounts for a specific device
# This file is included by cleanup_local_accounts.yml for each device

- name: "🔍 Discover | Get local domains for device {{ device_item.device_name }}"
  uri:
    url: "{{ wallix_api.base_url }}/devices/{{ device_item.device_name }}/localdomains"
    method: GET
    headers:
      Cookie: "{{ wallix_session_cookie }}"
    validate_certs: "{{ wallix_auth.connection.verify_ssl | default(false) }}"
    timeout: 30
    status_code: [200, 404]
    return_content: yes
  register: device_domains_result
  failed_when: false

- name: "🔍 Discover | Get local accounts for each domain in device {{ device_item.device_name }}"
  uri:
    url: "{{ wallix_api.base_url }}/devices/{{ device_item.device_name }}/localdomains/{{ domain_item.domain_name }}/accounts"
    method: GET
    headers:
      Cookie: "{{ wallix_session_cookie }}"
    validate_certs: "{{ wallix_auth.connection.verify_ssl | default(false) }}"
    timeout: 30
    status_code: [200, 404]
    return_content: yes
  loop: "{{ device_domains_result.json | default([]) }}"
  loop_control:
    loop_var: domain_item
  register: device_accounts_result
  failed_when: false
  when: 
    - device_domains_result.status == 200
    - device_domains_result.json is defined

- name: "🗑️ Discover | Add accounts to deletion list for device {{ device_item.device_name }}"
  set_fact:
    local_accounts_to_delete: "{{ local_accounts_to_delete + [account_info] }}"
  loop: "{{ device_accounts_result.results | default([]) | subelements('json', skip_missing=True) }}"
  loop_control:
    loop_var: account_pair
  when: 
    - device_accounts_result.results is defined
  vars:
    domain_result: "{{ account_pair.0 }}"
    account_item: "{{ account_pair.1 }}"
    account_info: {
      'device_name': '{{ device_item.device_name }}',
      'device_id': '{{ device_item.id }}',
      'domain_name': '{{ domain_result.domain_item.domain_name }}',
      'domain_id': '{{ domain_result.domain_item.id }}',
      'account_name': '{{ account_item.account_name }}',
      'account_id': '{{ account_item.id }}',
      'account_identifier': '{{ device_item.device_name }}/{{ domain_result.domain_item.domain_name }}/{{ account_item.account_name }}'
    }