---
# WALLIX Cleanup - Generate Report Tasks

- name: "📊 Report | Initialize cleanup report"
  set_fact:
    wallix_cleanup_report:
      timestamp: "{{ ansible_date_time.iso8601 }}"
      bastion_url: "{{ wallix_api.base_url }}"
      operation_mode: "{{ wallix_cleanup.operation_mode }}"
      confirmation_required: "{{ wallix_cleanup.require_confirmation }}"
      backup_enabled: "{{ wallix_cleanup_backup.enabled }}"
      discovery_stats: "{{ wallix_discovery_stats | default({}) }}"
      cleanup_stats: "{{ wallix_cleanup_stats | default({}) }}"
      components_processed: []

- name: "📊 Report | Add authorization stats to report"
  set_fact:
    wallix_cleanup_report: >-
      {{
        wallix_cleanup_report | combine({
          'components_processed': wallix_cleanup_report.components_processed + [{
            'component': 'authorizations',
            'enabled': wallix_cleanup_components.authorizations.enabled | default(false),
            'processed': wallix_cleanup_stats.authorizations_processed | default(0),
            'deleted': wallix_cleanup_stats.authorizations_deleted | default(0),
            'errors': wallix_cleanup_stats.authorizations_errors | default(0)
          }]
        })
      }}
  when: wallix_cleanup_components.authorizations.enabled | default(false)

- name: "📊 Report | Add target group stats to report"
  set_fact:
    wallix_cleanup_report: >-
      {{
        wallix_cleanup_report | combine({
          'components_processed': wallix_cleanup_report.components_processed + [{
            'component': 'target_groups',
            'enabled': wallix_cleanup_components.target_groups.enabled | default(false),
            'processed': wallix_cleanup_stats.target_groups_processed | default(0),
            'deleted': wallix_cleanup_stats.target_groups_deleted | default(0),
            'errors': wallix_cleanup_stats.target_groups_errors | default(0)
          }]
        })
      }}
  when: wallix_cleanup_components.target_groups.enabled | default(false)

- name: "📊 Report | Add user group stats to report"
  set_fact:
    wallix_cleanup_report: >-
      {{
        wallix_cleanup_report | combine({
          'components_processed': wallix_cleanup_report.components_processed + [{
            'component': 'user_groups',
            'enabled': wallix_cleanup_components.user_groups.enabled | default(false),
            'processed': wallix_cleanup_stats.user_groups_processed | default(0),
            'deleted': wallix_cleanup_stats.user_groups_deleted | default(0),
            'errors': wallix_cleanup_stats.user_groups_errors | default(0)
          }]
        })
      }}
  when: wallix_cleanup_components.user_groups.enabled | default(false)

- name: "📊 Report | Add local account stats to report"
  set_fact:
    wallix_cleanup_report: >-
      {{
        wallix_cleanup_report | combine({
          'components_processed': wallix_cleanup_report.components_processed + [{
            'component': 'local_accounts',
            'enabled': wallix_cleanup_components.devices.enabled | default(false),
            'processed': wallix_cleanup_stats.local_accounts_processed | default(0),
            'deleted': wallix_cleanup_stats.local_accounts_deleted | default(0),
            'errors': wallix_cleanup_stats.local_accounts_errors | default(0)
          }]
        })
      }}
  when: wallix_cleanup_components.devices.enabled | default(false)

- name: "📊 Report | Add device stats to report"
  set_fact:
    wallix_cleanup_report: >-
      {{
        wallix_cleanup_report | combine({
          'components_processed': wallix_cleanup_report.components_processed + [{
            'component': 'devices',
            'enabled': wallix_cleanup_components.devices.enabled | default(false),
            'processed': wallix_cleanup_stats.devices_processed | default(0),
            'deleted': wallix_cleanup_stats.devices_deleted | default(0),
            'errors': wallix_cleanup_stats.devices_errors | default(0)
          }]
        })
      }}
  when: wallix_cleanup_components.devices.enabled | default(false)

- name: "📊 Report | Add user stats to report"
  set_fact:
    wallix_cleanup_report: >-
      {{
        wallix_cleanup_report | combine({
          'components_processed': wallix_cleanup_report.components_processed + [{
            'component': 'users',
            'enabled': wallix_cleanup_components.users.enabled | default(false),
            'processed': wallix_cleanup_stats.users_processed | default(0),
            'deleted': wallix_cleanup_stats.users_deleted | default(0),
            'errors': wallix_cleanup_stats.users_errors | default(0)
          }]
        })
      }}
  when: wallix_cleanup_components.users.enabled | default(false)

- name: "📊 Report | Add domain stats to report"
  set_fact:
    wallix_cleanup_report: >-
      {{
        wallix_cleanup_report | combine({
          'components_processed': wallix_cleanup_report.components_processed + [{
            'component': 'domains',
            'enabled': wallix_cleanup_components.domains.enabled | default(false),
            'processed': wallix_cleanup_stats.domains_processed | default(0),
            'deleted': wallix_cleanup_stats.domains_deleted | default(0),
            'errors': wallix_cleanup_stats.domains_errors | default(0)
          }]
        })
      }}
  when: wallix_cleanup_components.domains.enabled | default(false)

- name: "📊 Report | Calculate total stats"
  set_fact:
    wallix_cleanup_stats: >-
      {{
        wallix_cleanup_stats | default({}) | combine({
          'total_processed': (
            (wallix_cleanup_stats.authorizations_processed | default(0)) +
            (wallix_cleanup_stats.target_groups_processed | default(0)) +
            (wallix_cleanup_stats.user_groups_processed | default(0)) +
            (wallix_cleanup_stats.local_accounts_processed | default(0)) +
            (wallix_cleanup_stats.devices_processed | default(0)) +
            (wallix_cleanup_stats.users_processed | default(0)) +
            (wallix_cleanup_stats.domains_processed | default(0))
          ),
          'total_deleted': (
            (wallix_cleanup_stats.authorizations_deleted | default(0)) +
            (wallix_cleanup_stats.target_groups_deleted | default(0)) +
            (wallix_cleanup_stats.user_groups_deleted | default(0)) +
            (wallix_cleanup_stats.local_accounts_deleted | default(0)) +
            (wallix_cleanup_stats.devices_deleted | default(0)) +
            (wallix_cleanup_stats.users_deleted | default(0)) +
            (wallix_cleanup_stats.domains_deleted | default(0))
          ),
          'total_errors': (
            (wallix_cleanup_stats.authorizations_errors | default(0)) +
            (wallix_cleanup_stats.target_groups_errors | default(0)) +
            (wallix_cleanup_stats.user_groups_errors | default(0)) +
            (wallix_cleanup_stats.local_accounts_errors | default(0)) +
            (wallix_cleanup_stats.devices_errors | default(0)) +
            (wallix_cleanup_stats.users_errors | default(0)) +
            (wallix_cleanup_stats.domains_errors | default(0))
          )
        })
      }}

- name: "📄 Report | Save cleanup report to file"
  copy:
    content: "{{ wallix_cleanup_report | to_nice_json }}"
    dest: "{{ wallix_cleanup_reporting.destination }}"
  delegate_to: localhost
  when: wallix_cleanup_reporting.enabled

- name: "📋 Report | Display cleanup summary"
  debug:
    msg:
      - "🧹 WALLIX Cleanup Report Summary"
      - "=================================="
      - "Timestamp: {{ wallix_cleanup_report.timestamp }}"
      - "Bastion: {{ wallix_cleanup_report.bastion_url }}"
      - "Mode: {{ wallix_cleanup_report.operation_mode }}"
      - ""
      - "Overall Statistics:"
      - "  Total processed: {{ wallix_cleanup_stats.total_processed | default(0) }}"
      - "  Total deleted: {{ wallix_cleanup_stats.total_deleted | default(0) }}"
      - "  Total errors: {{ wallix_cleanup_stats.total_errors | default(0) }}"
      - ""
      - "Report saved to: {{ wallix_cleanup_reporting.destination if wallix_cleanup_reporting.enabled else 'Report generation disabled' }}"