---
galaxy_info:
  author: WALLIX Automation Team
  description: WALLIX Bastion API Authentication Role
  company: WALLIX
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - wallix
    - bastion
    - security
    - authentication
    - api

dependencies: []